name: ping

on:
  workflow_dispatch:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: curl the url
        run: |
          echo "Pinging"
          curl "$URL"
